#### Topics to be covered today
- Binary Operations
- String Operations
- Mathematical Operations
- Stat Operations

In [1]:
import numpy as np

1a. Bitwise Operator

In [3]:
num1 = 10
num2 = 11
print("Number 1:", num1, "Binary:", np.binary_repr(num1))
print("Number 2:", num2, "Binary:", np.binary_repr(num2)) 
Bitwise_OR_operator = np.bitwise_or(num1, num2)
Bitwise_AND_operator = np.bitwise_and(num1, num2)
print("Bitwise_OR_operator:", Bitwise_OR_operator, "Binary Representation:", np.binary_repr(Bitwise_OR_operator))
print("Bitwise_AND_operator:", Bitwise_AND_operator, "Binary Representation:", np.binary_repr(Bitwise_AND_operator))

Number 1: 10 Binary: 1010
Number 2: 11 Binary: 1011
Bitwise_OR_operator: 11 Binary Representation: 1011
Bitwise_AND_operator: 10 Binary Representation: 1010


In [4]:
num1 = 10
num2 = 7
  
Bitwise_OR_operator = np.bitwise_or(num1, num2)
Bitwise_AND_operator = np.bitwise_and(num1, num2)
print("Bitwise_OR_operator:", Bitwise_OR_operator, "Binary Representation:", np.binary_repr(Bitwise_OR_operator))
print("Bitwise_AND_operator:", Bitwise_AND_operator, "Binary Representation:", np.binary_repr(Bitwise_AND_operator))

Bitwise_OR_operator: 15 Binary Representation: 1111
Bitwise_AND_operator: 2 Binary Representation: 10


2a. String operation - Add

In [8]:
str_array1 = np.array(['a1','b','c','d','e', 'a'])
str_array2 = np.array(['x','y','z','a','b', 'a'])
np.char.add(str_array1 , str_array2)

array(['a1x', 'by', 'cz', 'da', 'eb', 'aa'], dtype='<U3')

In [9]:
str_array1 = np.array(['a','b','c','d','e'])
str_array2 = 'a'
np.char.add(str_array1 , str_array2)

array(['aa', 'ba', 'ca', 'da', 'ea'], dtype='<U2')

2b. String operation - Multiply

In [12]:
str_array1 = np.array(['ab','b','c','d','e'])
np.char.multiply(str_array1 , 4)

array(['abababab', 'bbbb', 'cccc', 'dddd', 'eeee'], dtype='<U8')

2c. String operation - Capitalize

In [13]:
np.char.capitalize('learn data science')

array('Learn data science', dtype='<U18')

In [14]:
np.char.capitalize(np.char.multiply(str_array1 , 3))

array(['Ababab', 'Bbb', 'Ccc', 'Ddd', 'Eee'], dtype='<U6')

2d. String operation - Change of Case (lower to upper case and vice-versa)

In [16]:
#np.char.upper(str_array1)
np.char.lower(str_array1)

array(['ab', 'b', 'c', 'd', 'e'], dtype='<U2')

2e. String Operation - Strip the empty spaces

In [17]:
str_array3 = np.array(['  x   ',' y ',' z ',' a  ','  b   '])
print(str_array3)
print(np.char.strip(str_array3))

['  x   ' ' y ' ' z ' ' a  ' '  b   ']
['x' 'y' 'z' 'a' 'b']


2f. String Operation - Replace

In [19]:
np.char.replace (str_array3, 't', 'a')

array(['  x   ', ' y ', ' z ', ' a  ', '  b   '], dtype='<U6')

3a. Mathe,atical operation

In [22]:
m_array1 = np.array([1,2,3,4,5])
m_array2 = np.array([2,2,2,2,2])

print("Addition:", m_array1 + m_array2)
print("Multiplication:", m_array1 * m_array2)
print("Subtract:", m_array1 - m_array2)

Addition: [3 4 5 6 7]
Multiplication: [ 2  4  6  8 10]
Subtract: [-1  0  1  2  3]


3b. Round-off

In [23]:
m_array3 = np.array([2.122,6.23423,7.343,9.5465,11.343])
print("Round-off:", np.around(m_array3, decimals = 2))
print("Floor:", np.floor(m_array3))
print("Ceil:", np.ceil(m_array3))

Round-off: [ 2.12  6.23  7.34  9.55 11.34]
Floor: [ 2.  6.  7.  9. 11.]
Ceil: [ 3.  7.  8. 10. 12.]


3c. Power

In [25]:
m_array1 = np.array([1,2,3,4,5])
m_array2 = np.array([2,2,2,2,2])
print(np.power(m_array1,m_array2))
print(np.power(m_array1,2))

[ 1  4  9 16 25]
[ 1  4  9 16 25]


4a. Stat Operations -  Min and Max

In [26]:
m_array4 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]) 
print("Min:", np.amin(m_array4))
print("Max:", np.amax(m_array4))

Min: 1
Max: 15


4b. Stat Operations - Min and Max with Axis

In [31]:
print(m_array4)
print("Min:", np.amin(m_array4, axis = 1)) # Second parameter is Axis
print("Max:", np.amax(m_array4, axis = 0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Min: [ 1  6 11]
Max: [11 12 13 14 15]


4c. Stat Operations - Median

In [32]:
print("Median:", np.median(m_array4, 1))

Median: [ 3.  8. 13.]


4d. Stat Operations - Average, Mean and Variance

In [34]:
print("Average:", np.average(m_array4, 0))
print("Mean:", np.mean(m_array4, 0))
print("Variance:", np.var(m_array4, 0))

Average: [ 6.  7.  8.  9. 10.]
Mean: [ 6.  7.  8.  9. 10.]
Variance: [16.66666667 16.66666667 16.66666667 16.66666667 16.66666667]


4d. Stat Operations - Percentile

In [36]:
print("Percentile:", np.percentile(m_array4, 100, axis = 0))

Percentile: [11. 12. 13. 14. 15.]


#### To Try
- Create a set of 1-D, 2-D and 3-D array
- Repeat all the above operation with the above created arrays