#### Topics to be covered today
- Introduction to Numpy
     - Means Numerical Python, can be considered as an python replacement for          Matlap
     - Useful while working on linear algebra, matrix operations and fourier          transformation

- Numpy is faster than list
     - Numpy is estimated to be around 30 times faster than python list
     - Packed closely in memory
     - Homogeneous
     - Optimized for recent computer architecture


In [1]:
import numpy as np

1a. One Dimentional Array

In [2]:
array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(type(array1d))

<class 'numpy.ndarray'>


In [3]:
print(array1d)

[ 1  2  3  4  5  6  7  8  9 10]


1b. Two Dimensional Array

In [6]:
array2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(array2d)
print("Array Shape: ", array2d.shape)
print("Dimensions: ", array2d_2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array Shape:  (2, 5)
Dimensions:  2


In [5]:
array2d_2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(array2d_2)
print("Array Shape: ", array2d_2.shape)
print("Dimensions: ", array2d_2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Array Shape:  (3, 5)
Dimensions:  2


1c. Three Dimensional Array

In [8]:
array3d = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(array3d)
print("Array Shape: ", array3d.shape)
print("Dimensions: ", array3d.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
Array Shape:  (3, 2, 5)
Dimensions:  3


1d. Reshaping an Array

In [12]:
array1 = np.arange(24)
print(array1)
print("Array Shape: ", array1.shape)
print("Number of Dimensions:", array1.ndim)


array2 = array1.reshape(3,2,4) 
print(array2)
print("Array Shape: ", array2.shape)
print("Number of Dimensions:", array2.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Array Shape:  (24,)
Number of Dimensions: 1
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
Array Shape:  (3, 2, 4)
Number of Dimensions: 3


2a. Array is homogeneous

In [14]:
array3 = np.array([1, 2, 3, 4])
print(array3.dtype)
print(array3*2)

int32
[2 4 6 8]


In [16]:
array4 = np.array([1, 2, 3, 4, "a"])
print(array4.dtype) # U - Unincode String
print(array4*2)

<U11


UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

2b. Define Data Type

In [18]:
array5 = np.array([1, 2, 3, 4], dtype='i4') # Integer of 2 Bytes
print(array5)
print(array5.dtype)

[1 2 3 4]
int32


2c. Pass character to Array defined as Integer

In [19]:
array6 = np.array([1, 2, 3, 4, "a"], dtype='i2') # Integer of 2 Bytes
print(array6)
print(array6.dtype)

ValueError: invalid literal for int() with base 10: 'a'

2d. Convert Integer Array to Float

In [20]:
array7_i = np.array([1, 2, 3])
array7_f = array7_i.astype('f')
print(array7_f)
print(array7_f.dtype)

[1. 2. 3.]
float32


2e. Convert Float Array to Integer

In [22]:
array8_f = np.array([1.2, 2.2, 3.9])
array8_i = array8_f.astype('i')
print(array8_i)
print(array8_i.dtype)

[1 2 3]
int32
