#### Topics for today
- Indexing
- Slicing
- Join
- Split

In [1]:
import numpy as np

1a. Create 3 array of 1-Dim, 2-Dim and 3-Dim

In [2]:
array1 = np.arange(20)
print(array1)
print("Array Shape: ", array1.shape)
print("Number of Dimensions:", array1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array Shape:  (20,)
Number of Dimensions: 1


In [3]:
array2 = array1.reshape(2,10) 
print(array2)
print("Array Shape: ", array2.shape)
print("Number of Dimensions:", array2.ndim)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
Array Shape:  (2, 10)
Number of Dimensions: 2


In [4]:
array3 = array1.reshape(2,2,5) 
print(array3)
print("Array Shape: ", array3.shape)
print("Number of Dimensions:", array3.ndim)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
Array Shape:  (2, 2, 5)
Number of Dimensions: 3


1b. Using Index in Array

In [5]:
print(array1)
print("Element in 3rd Position", array1[2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Element in 3rd Position 2


1c. Index in 2 dimensional Array

In [7]:
print(array2)
print('5th element on 2nd dim: ', array2[1, 4])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
5th element on 2nd dim:  14


1d. Index n 3 dimensional Array

In [8]:
print(array3)
print('5th element on 2nd dim in the first array: ', array3[0, 1, 4])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
5th element on 2nd dim in the first array:  9


1e. Negative Indexing

In [9]:
print(array2)
print('Last element from 2nd dim: ', array2[1, -1])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
Last element from 2nd dim:  19


2a. Slicing

In [10]:
print(array1)
print(array1[:7])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6]


2b. Slicing a one dimensional array from a 2 dimensinal array

In [11]:
print(array2)
print(array2[0, 1:4])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[1 2 3]


2c. Slicing a two dimensional array from a 2 dimensinal array

In [12]:
print(array2)
print(array2[:, 1:4])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 1  2  3]
 [11 12 13]]


3a. Joining 1-dimensional array by using Concatination

In [13]:
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([6, 7, 8, 9, 10])
new_data1 = np.concatenate((data1, data2))
print(new_data1)

[ 1  2  3  4  5  6  7  8  9 10]


3b. Joining 2-dimensional array by using Concatination

In [14]:
data1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
data2 = np.array([[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]])
new_data1 = np.concatenate((data1, data2))
print(new_data1)

[[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]


3c. Joining 2-dimensional array by using Concatination with Axis parameter

In [20]:
data1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
data2 = np.array([[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]])
new_data2 = np.concatenate((data1, data2), axis = 1)
print(new_data2)
print(new_data2.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
(2, 10)


3d. Joining using Stack Function

In [19]:
data1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
data2 = np.array([[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]])
new_data3 = np.stack((data1, data2))
print(new_data3)
print(new_data3.shape)

[[[ 1  2  3  4  5]
  [ 1  2  3  4  5]]

 [[ 6  7  8  9 10]
  [ 6  7  8  9 10]]]
(2, 2, 5)


3e. To stack by rows

In [22]:
data1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
data2 = np.array([[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]])
new_data4 = np.hstack((data1, data2))
print(new_data4)
print(new_data4.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
(2, 10)


3f. To stack by columns

In [24]:
data1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
data2 = np.array([[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]])
new_data5 = np.vstack((data1, data2))
print(new_data5)
print(new_data5.shape)

[[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
(4, 5)


4a. Splitting

In [26]:
data = np.array([1, 2, 3, 4, 5, 6])
new_array1 = np.array_split(data, 3)
print(new_array1)
print(new_array1[0])
print(new_array1[1])
print(new_array1[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


4b. Splitting 2-dimensional array

In [27]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
new_array2 = np.array_split(data, 3)
print(data)
print(new_array2)
print(new_array2[0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[[1 2 3]
 [4 5 6]]


4c. Splitting 2-dimensional array based on axis

In [28]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
new_array3 = np.array_split(data, 3, axis = 1)
print(data)
print(new_array3)
print(new_array3[0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
