#### Topics Covered today
- Iteration
- Manipulation
- Random Number and Distribution

In [1]:
import numpy as np

1a. Iterate over a 1-dimensional array

In [3]:
array1 = np.array([1, 2, 3, 4, 5])
i = 0
for x in array1:
    print(x)
    i = i+1
    print(i)

1
1
2
2
3
3
4
4
5
5


1b. Iterate over 2-dimensional array

In [7]:
array2 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[6, 7, 8, 9, 10]])
print(array2)
i = 0
for x in array2:
    print(x)
    i = i + 1
    print (i)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
1
[ 6  7  8  9 10]
2
[ 6  7  8  9 10]
3


1c. Iterate by elements in a 2-dimensional array

In [8]:
array3 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
for i in array3:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


1d. Iterate over 3-dimensional array

In [10]:
array4 = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]])
print(array4)
i = 0
for x in array4:
    print(x)
    i = i + 1
    print (i)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


1e. Accessing all the elements in a 3-d array using loop

In [11]:
array5 = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]])

for i in array5:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


1f. Using nditer and loop through the array

In [13]:
array6 = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]])
z = 0
for i in np.nditer(array6):
    print(i)
    z = z +1
    print(z)

1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
10
1
11
2
12
3
13
4
14
5
15
6
16
7
17
8
18
9
19
10
20


Manipulation <br>
2a. Reshape (1-D to higher dimension)

In [24]:
m_array1 = np.arange(30)
print(m_array1)
m_array2 = m_array1.reshape(3,10) 
print(m_array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


2b. Reshape (Higher dimension to 1-D)

In [22]:
m_array3 = m_array2.flatten()
print(m_array3)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

2c. Transpose

In [25]:
print(m_array2)
print(m_array2.T)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]]


2d. Roll Axis

In [26]:
print(np.rollaxis(m_array2,1))

[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]]


2e. Join, Slice and Splitting

3a. Random Numbers

In [28]:
from numpy import random

In [31]:
random.rand()

0.631776730868861

3b. Random 1-D Array

In [32]:
r_array1 = random.randint(25, size=(5))
print(r_array1)

[17 20 13 17 18]


3c. Random 2-D Array

In [33]:
r_array2 = random.randint(250, size=(5, 5))
print(r_array2)

[[118  24   5 216 114]
 [112 182  15   2  73]
 [229  74 199  30  73]
 [110  93 118 222  97]
 [221 228   6  98 222]]


3d. Random Array with a specific distribution

In [34]:
r_array3 = random.choice([1, 2, 3, 4, 5], p=[0.1, 0.2, 0.4, 0.2, 0.1], size=(100))
print(r_array3)

[3 2 4 1 4 1 1 1 5 3 3 4 3 1 3 3 3 3 2 5 5 3 1 3 2 3 3 3 4 4 3 3 3 1 3 4 2
 1 5 2 3 5 4 3 1 4 1 3 3 3 3 3 3 2 2 4 3 2 4 3 3 4 3 3 2 1 2 5 2 2 3 5 5 1
 1 2 2 5 3 4 4 3 3 2 3 5 3 3 1 3 3 2 2 1 4 3 3 2 2 3]


##To Do
- Create an 1-D array of length 100 and print only the even number (Hint - Use Iteration)
- Create an 1-D array with random values and convert it into an 3-D array
- Try roll axis on the abve 3-D array
- Try transpose on the above 3-D array